[mypy]
python_version = 3.11
warn_return_any = false
ignore_missing_imports = false

[mypy-pyghidra.*]
ignore_missing_imports = true

[mypy-capstone.*]
ignore_missing_imports = true

[mypy-fixtures.*]
ignore_missing_imports = true
